apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
 name: {{.Values.name}}-http-route
 annotations:
   konghq.com/strip-path: 'true'
spec:
 parentRefs:
 - name: kong
 rules:
 - matches:
     - path:
         type: PathPrefix
         value: /{{.Values.name}}
   backendRefs:
   - name: {{.Values.name}}-service
     kind: Service
     port: {{.Values.port}}


