apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}-secret
type: Opaque
data:
  DJANGO_SECRET_KEY: {{.Values.secret_key | b64enc | quote}}
  DATABASE_URL: {{.Values.database_url | b64enc | quote}}
