apiVersion: v1
kind: Secret
metadata:
  name: order-secret
type: Opaque
data:
  POSTGRES_DB: ZGI=
  POSTGRES_USER: dXNlcg==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  DJANGO_SECRET_KEY: c2VjcmV0X2tleQ==
  DATABASE_URL: cG9zdGdyZXM6Ly91c2VyOnBhc3N3b3JkQG9yZGVyLWRiOjU0MzIvZGI=
