apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      name: order
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: hugobrilhante/saga-pattern:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: order-config-map
            - secretRef:
                name: order-secret
          resources:
            limits:
              cpu: "2"
              memory: "1024Mi"
            requests:
              cpu: "1"
              memory: "512Mi"
      initContainers:
        - name: migrations
          image: hugobrilhante/saga-pattern:v2
          command: [ "/bin/sh" ]
          args:
            - "-c"
            - python manage.py migrate
          envFrom:
            - configMapRef:
                name: order-config-map
            - secretRef:
                name: order-secret
        - name: loaddata
          image: hugobrilhante/saga-pattern:v2
          command: [ "/bin/sh" ]
          args:
            - "-c"
            - python manage.py loaddata order
          envFrom:
            - configMapRef:
                name: order-config-map
            - secretRef:
                name: order-secret
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: order
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP