replicas: 1

image:
  repository: "hugobrilhante/payment"
  pullPolicy: Always
  tag: "v1"

name: "payment"

port: 8002

secret_key: "secret_key"

postgres:
  db: "db"
  user: "user"
  password: "password"

database_url: "postgres://user:password@payment-db-service:5432/db"