services:
  payment-service:
    build:
      context: .
    ports:
      - 8002:8002
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - saga
    depends_on:
      payment-db:
        condition: service_healthy
  payment-db:
    image: postgis/postgis:16-3.4
    platform: linux/amd64
    restart: always
    volumes:
      - payment-db-data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - saga
volumes:
  payment-db-data:

networks:
  saga:
    driver: bridge