# Generated by Django 4.2.8 on 2024-01-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
