# Generated by Django 4.2.8 on 2024-01-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=20)),
                ('product_id', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('reserve', 'Reserve Stock'), ('waiting', 'Waiting Payment'), ('confirmed', 'Payment Confirmed'), ('rejected', 'Out of Stock')], default='created', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
