apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  replicas: 1
  rabbitmq:
    additionalConfig: |
      default_user=guest
      default_pass=guest
    additionalPlugins:
      - rabbitmq_management
      - rabbitmq_stomp
      - rabbitmq_shovel
      - rabbitmq_shovel_management
