# Default values for saga.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: "v1"

name: "app"

port: 8000

# To simplify my examples. There are other means for the correct use of credentials.
secret_key: "secret_key"

postgres:
  db: "db"
  user: "user"
  password: "password"

database_url: "postgres://user:password@db-service:5432/db"