services:
  payment-service:
    build:
      context: .
    ports:
      - 8002:8002
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - saga
    depends_on:
      payment-db:
        condition: service_healthy
  payment-publish:
    build:
      context: .
    command: [ "python", "manage.py", "publish" ]
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - saga
    depends_on:
      payment-db:
        condition: service_healthy
  payment-subscribe:
    build:
      context: .
    command: [ "python", "manage.py", "subscribe", "src.core.callback.callback", "/exchange/saga/payment.v1", "payment.v1" ]
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - saga
    depends_on:
      payment-db:
        condition: service_healthy
  payment-db:
    image: postgres:16
    platform: linux/amd64
    restart: always
    volumes:
      - payment-db-data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-db}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - saga
volumes:
  payment-db-data:

networks:
  saga:
    driver: bridge