  # a very minimal declarative config file
_format_version: "2.1"
_transform: true

services:
- name: order
  url: http://order:8000
  routes:
  - name: order
    paths:
    - /order
- name: stock
  url: http://stock:8001
  routes:
  - name: stock
    paths:
    - /stock
- name: payment
  url: http://payment:8002
  routes:
  - name: payment
    paths:
    - /payment
plugins:
- name: cors
  config:
   origins:
   - "*"
   methods:
   - GET
   - POST
   headers:
   - Accept
   - Accept-Version
   - Content-Length
   - Content-MD5
   - Content-Type
   - Date
   - X-Auth-Token
   exposed_headers:
   - X-Auth-Token
   credentials: true
   max_age: 3600
